---
- name: Install Postfix
  become: true
  apt:
    name: postfix
    state: latest
###
- name: Update Postfix configuration
  become: true
  lineinfile:
    path: "/etc/postfix/main.cf"
    state: present
    regexp: "^{{ item.name }} ?="
    line: "{{ item.name }} = {{ item.value }}"
  with_items:
    - { name: 'myhostname', value: "yarnika.ru" }
    - { name: 'mydestination', value: "_ALL_, $myhostname, localhost.localdomain, localhost" }
  notify: Restart Postfix